version: "3.9"

services:
  web:
    build: .
    container_name: photo_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static/uploads:/app/static/uploads
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=photography_portfolio
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: photo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: photography_portfolio
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
